### PR TITLE
Improve compatibility to memos 0.25.3.

### LINKED ISSUE #8: Mortis 0.25.3 fails with Memos 0.25.3 stable: WorkspaceService Unimplemented
Mortis 0.25.3 claims compatibility with Memos 0.25.3, but when deployed against the stable release of Memos 0.25.3, the frontend fails to load properly. The logs show repeated `Unimplemented` errors related to WorkspaceService, which appears to have been removed or refactored in Memos 0.25.3 stable.

### Environment
- Mortis version: ghcr.io/mudkipme/mortis:0.25.3
- Memos version: neosmemo/memos:0.25.3 (stable)
- Deployment method: Docker Compose + Nginx Proxy Manager
- Frontend access: via proxied domain
- Browser: Chrome (also tested in incognito)

### Steps to Reproduce
1. Deploy Memos 0.25.3 stable.
2. Deploy Mortis 0.25.3.
3. Access Mortis frontend.
4. Observe frontend failure and backend logs.

### Actual Behavior
- Frontend fails to load.
- Backend logs show:

2025/11/29 16:47:20 ERROR failed to get workspace profile error="rpc error: code = Unimplemented desc = unknown service memos.api.v1.WorkspaceService"

- Mortis cannot retrieve workspace profile or settings.

### Expected Behavior
- Mortis should be able to connect and function with Memos 0.25.3 stable.
- Workspace profile and settings should be accessible via supported APIs.

### Additional Notes
- Mortis works correctly with Memos 0.25.2.
- The issue seems to stem from Mortis relying on `WorkspaceService`, which is no longer present in Memos 0.25.3 stable.
- Possibly Mortis was tested against Memos dev/nightly builds rather than the stable release.
- Happy to assist with testing or provide further logs if needed.

### PR DESCRIPTION
**Pull request by dhufe**
Hey there,

This PR fixes #8 by ensuring API compatibility for memos 0.25.3.

**Changes:**
- Replaced WorkspaceService by InstanceService proto definitions with the existing API structure
- Fixed proto compilation errors from conflicting message definitions

The API endpoints should now work seamlessly with existing clients.

Let me know if you'd like any adjustments!

### CODE REVIEW

**Comment by dhufe** [comment]
Looks like you already fixed this.

Closing this as duplicate. Thanks for the quick fix! 👍
